hotfix: prevent user from typing negative number or 0 as house number
andrealvescorreia/padaflix pull request #84
Opened 2023-11-24 17:00 UTC by andrealvescorreia

Hotfix de um erro grave no sistema onde o usuario pode inserir numero negativo no endereco. Então o merge vai pro main, e depois manda pra develop.

No back, em Endereco mudei 'numero' de CharField para IntegerField e adicionei validação que permite apenas numeros maiores ou iguais a 1.
Também atualizei os testes unitários para refletir essa mudança.
Como o back mudou, execute o comando `python manage.py migrate` uma vez.

2023-11-24 17:12 UTC, Artur906 requested changes
Precisamos resolver o novo bug que surgiu, fora isso ficou muito bom

2023-11-24 17:12 UTC, Artur906 commented on frontend/src/components/AddressForm/index.tsx
temos um bug aqui, quando eu digito um número e apago, ele fica como NAN, e não tem mais como editar o conteúdo

2023-11-24 17:14 UTC, Artur906 commented on frontend/src/components/AddressForm/index.tsx
Suspeito que é porque ele está tendando dar parse em um valor nulo, na hora que eu apago o número

2023-11-24 17:35 UTC, andrealvescorreia commented on frontend/src/components/AddressForm/index.tsx
por isso que é bom o code review kkkk

2023-11-24 17:39 UTC, Artur906 commented on frontend/src/components/AddressForm/index.tsx
é kkkkk

2023-11-24 17:41 UTC, Artur906 reviewed
Esse foi resolvido, mas eu achei outro ;-; 
depois que você digita o primeiro número você pode inserir qualquer caractere

2023-11-24 18:19 UTC, Artur906 reviewed
Por algum motivo o valor de numero está ficando nulo

2023-11-24 19:06 UTC, andrealvescorreia commented
Programação é minha paixão 🥰🥰 
Kkkkkk eu acho q sei como resolver, amanhã faço

2023-11-25 13:18 UTC, andrealvescorreia commented
Em teoria deve funcionar agora

2023-11-25 13:54 UTC, Artur906 requested changes
só tem um problema agora, se o usuário digitar uma letra ele vai virar NAN

2023-11-25 13:54 UTC, Artur906 commented on frontend/src/components/AddressForm/index.tsx
> +                            if (numberInput === '')
Testei aqui e colocar uma verificação assim vai resolver o problema
```jsx
if (numberInput === '' || numberInput.match(RegExp('^[0-9]')))
```

2023-11-25 14:20 UTC, andrealvescorreia commented on frontend/src/components/AddressForm/index.tsx
> +                            if (numberInput === '')
Socorro meu Deus

2023-11-25 14:24 UTC, andrealvescorreia commented on frontend/src/components/AddressForm/index.tsx
> +                            if (numberInput === '')
testei 
if (numberInput === '' || numberInput.match(RegExp('^[0-9]')))
mas nao resolveu

2023-11-25 14:28 UTC, andrealvescorreia commented
vei se agora nao for eu desisto de ser programador

2023-11-25 14:57 UTC, Artur906 approved these changes
100% kkkkkk

2023-11-25 15:46 UTC, andrealvescorreia commented
vou estourar um champaing

2023-11-25 15:47 UTC, merged